### ISSUE TITLE
mnist_self_compression.ipynb【AttributeError: module 'tinygrad.nn' has no attribute 'BatchNorm'】

### ISSUE THREAD

**Issue by mintisan** [geohot/ai-notebooks#13]
When I run mnist_self_compression.ipynb, I encounter the following error. I searched through the issues on tinygrad but couldn't find anything. Is there something wrong with my version?

tinygrad version ： 0.9.1
-----------------------
python version： 3.9
OS ：macOS
-----------------------
python version： 3.10
OS ：Windows
-----------------------

I tried the above environments on Windows or macOS, as well as different Python versions, and encountered the same error.

```
Traceback (most recent call last):
  File "/Users/mintisan/Workplaces/ai-notebooks/mnist_self_compression.py", line 52, in <module>
    model = Model()
  File "/Users/mintisan/Workplaces/ai-notebooks/mnist_self_compression.py", line 40, in __init__
    nn.BatchNorm(32, affine=False, track_running_stats=False),
AttributeError: module 'tinygrad.nn' has no attribute 'BatchNorm'
```

**Comment by mintisan** [comment]
use BatchNorm2d when use 0.9.1 version
